### ISSUE TITLE
Rendering colors on JVM (anything other than a hex string)

### ISSUE THREAD

**Issue by niamu** [noprompt/garden#114]
There are [references within the project code](https://github.com/noprompt/garden/blob/5801aa52e833e8ab33ff1b0b74cc5009749105fd/test/garden/compiler_test.cljc#L62) currently that point to how color functions should get rendered:

```clojure
(color/hsla 30 40 50 0.5)
```

should become...

```css
"hsla(30, 40%, 50%, 0.5)"
```

But whenever I attempt to have my CSS render colors as in this short example it doesn't get properly formatted:

```clojure
(css [:body {:color (color/hsla 30 40 50 0.5)}])
```

becomes:

```css
"body{color:red:;green:;blue:;hue:30;saturation:40;lightness:50;alpha:.5}"
```

...instead of what I expect to be outputted which would be:

```css
"body{color:hsla(30, 40%, 50%, 0.5)}"
```

Similar incorrect results happen when using `hsl`, `rgb`, and `rgba`. I typically resort to wrapping all of my colours in `as-hex` or doing ugly string manipulations to get the desired alpha channel to render correctly as a valid CSS color string.

Am I doing something incorrectly? Or is this a bug that needs fixing?
