### ISSUE TITLE
RGBA and HSLA are compiled incorrectly

### ISSUE THREAD

**Issue by levitanong** [noprompt/garden#116]
e.g.

``` clj
{:box-shadow [[0 0 (px 8) (rgba 0 0 0 0.2)]]}
```

is converted to:

``` css
box-shadow: 0 0 8px hsla(0,0,0,0.2);
```

**Comment by noprompt** [comment]
I think that was intentional and, I do admit, is probably surprising. It's been a while but I think my rational was that `rgba` and `hsla`, when supported, are typically in supported tandem by the browser and that HSLA is a simpler model to understand with respect to color than RGBA. 

The RGBA model, in my opinion, places more of a cognitive load on the reader since they need to mix the colors in their head. The HSLA model on the other hand only requires an understanding of the color wheel it's based on, the angle (modulo 360), and then adjustment of saturation. IIRC most of the color operations are computed in terms of HSL because of it's simplicity.

Again, this is my personal opinion and I understand if it's confusing or surprising. If it's important the design can be adjusted to persist a `rgba` instead of `hsla`.

**Comment by ejlo** [comment]
Saturation and lightness should be percentages, though. It seems the % is dropped when the value is zero, which creates an invalid property value.

**Comment by noprompt** [comment]
@ejlo I'm not certain that it is invalid. My memory could be off but I don't recall that being the case in the CSS spec.

**Comment by noprompt** [comment]
@ejlo See [here](https://www.w3.org/TR/css3-color/#rgba-color).

```css
em { color: rgb(255,0,0) }      /* integer range 0 - 255 */
em { color: rgba(255,0,0,1)     /* the same, with explicit opacity of 1 */
em { color: rgb(100%,0%,0%) }   /* float range 0.0% - 100.0% */
em { color: rgba(100%,0%,0%,1) } /* the same, with explicit opacity of 1 */
```

It isn't clear to me if `0` and `0%` are legally interchangeable with respect to the spec or if it is something left up to browsers to handle. The fact the YUI compressor will convert `0%` to `0` does give me some confidence that this shouldn't be a problem.
