### ISSUE TITLE
Write an @supports block

### ISSUE THREAD

**Issue by 0tus** [noprompt/garden#165]
Hello,

I tried to translate this piece of CSS to Garden but couldn't figure out how to do :

```css
@supports ((position: -webkit-sticky) or (position: sticky)) {
  .sidebar-sticky {
    position: -webkit-sticky;
    position: sticky;
  }
}
```

This comes from the Dashboard example from Bootstrap 4 (in `dashboard.css`)

Is there a general way to write a block like this :

```
@<name> (<conditions>) {
  <rules>
}
```
Meanwhile I cheated with

```clojure
(str
  (css ...)
  (clojure.string/replace "@supports ..." #"\s*" "")
  (css ...))
```

Thank you very much
