### ISSUE TITLE
Incorrect handling of selectors

### ISSUE THREAD

**Issue by WilliamBehrens** [noprompt/garden#198]
The clojure expression
```clj
 (css [:.nav-button {:transition-duration "0.4s"}
       :.nav-button:hover {:background-color (map2rgba (:foreground colors))
                           :color (map2rgba (:background colors))}])
```
evaluates to
```css
.nav-button {
  transition-duration: 0.4s;
  background-color: rgba(217, 208, 242, 100);
  color: rgba(66, 59, 89, 100);
}
```
rather than
```css
.nav-button {
  transition-duration: 0.4s;
}
.nav-button:hover {
  background-color: rgba(217, 208, 242, 100);
  color: rgba(66, 59, 89, 100);
}
```
