### ISSUE TITLE
Incorrect css generation 

### ISSUE THREAD

**Issue by WilliamBehrens** [noprompt/garden#199]
```clj
(css [:main {:background-color "white"
             :margin-left "4vw"
             :margin-right "4vw"
             :width "100%"
             :height "100%"
             :padding "1vw"}
      :section {:width "100%"
                :height "100%"}
      :#me {:float "left"}
      :#desc {:float "right"
              :width "100%"
              :text-align "center"
              :align-items "center"
              :justify-content "center"}])
```
generates:
```css
main {
  background-color: "white";
  margin-left: 4vw;
  margin-right: 4vw;
  width: 100%;
  height: 100%;
  padding: 1vw;
  width: 100%;
  height: 100%;
  float: left;
  float: right;
  width: 100%;
  text-align: center;
  align-items: center;
  justify-content: center;
}
```
