### ISSUE TITLE
Feature request: Support for cascade layers

### ISSUE THREAD

**Issue by Jarzka** [noprompt/garden#205]
Hi

Modern CSS supports cascade layers that are useful for example overriding framework specific styles: https://developer.chrome.com/blog/cascade-layers/

I wonder if there is a support coming for this in Garden? Something like `at-layer` could be a reasonable way to implement this.

**Comment by Jarzka** [comment]
Let's say my site uses some 3rd party CSS framework as a base style. In this framework, there is a selector which adds a style for list items with links:

```css
.list > li > a {
  color: red;
}
```

Now I want to override the this style in my application code and turn the color into `blue`. A simple way to do this would be adding an utility class of `blue` to the element and creating the equivalent CSS class selector with Garden. The end result would be:

```cs
.blue {
  color: blue;
}
```

However, if I attach this `blue` class to my link item, it's still going to have `red` as a color, because the framework's selector `.list > li > a` is stronger than my own `.blue` selector. In order to override the red color, I would need to create a selector which is stronger than the one in the framework, something like `.list > li > a.blue`.

Cascade layers could make this process much simpler. I could wrap all the framework specific code into "framework" layer like so:

```css
@layer framework {
  .list > li > a {
    color: red;
  }
}

Then I would wrap all my application code into its own "application" layer, which comes after the "framework" layer like so:

```css
@layer application {
  .blue {
    color: blue;
  }
}
```

Now my `a` element turns into "blue" because the `@layer` rule creates its own cascading context, which automatically overrides all framework selectors, no matter how strong they are.
