### ISSUE TITLE
Improve at-font-face

### ISSUE THREAD

**Issue by noprompt** [noprompt/garden#37]
This seems like a start.

``` clj
(defn at-font-face [& {:as kwargs}]
  (let [kwargs (->> (select-keys kwargs [:family :weight :style :eot :woff :svg])
                    (remove (comp nil? second))
                    (into {}))
        font-attrs (select-keys kwargs [:family :weight :style])
        srcs (select-keys kwargs [:eot :woff :svg])
        url (cssfn :url)
        format (cssfn :format)]
    ["@font-face"
     {:font font-attrs}
     (when-not (empty? srcs)
       {:src (for [[fmt uri] srcs]
               [(url uri) (format (name fmt))])})]))

(at-font-face
 :family "Family"
 :weight :normal
 :style :normal
 :eot "/path/to/eot")
```

Result

``` css
@font-face {
  font-style: normal;
  font-weight: normal;
  font-family: Family;
  src: url(/path/to/eot) format(eot);
}
```

Edit: Add `url`
Edit: Add demonstration
