### ISSUE TITLE
How to handle "audio:not([controls])" in garden

### ISSUE THREAD

**Issue by erwagasore** [noprompt/garden#41]
``` css
/*
 * Prevents modern browsers from displaying 'audio' without controls
 * Remove excess height in iOS5 devices
 */

audio:not([controls]) {
    display: none;
    height: 0;
}
```
