### ISSUE TITLE
support for repeated declaration of same property

### ISSUE THREAD

**Issue by wilkerlucio** [noprompt/garden#54]
Hello,

I was trying here to use a cross-browser definition for `flex: box`, and in CSS terms it would be:

``` css
.flex-row {
  display: -webkit-box;
  display: -moz-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: box;
  display: flex;
}
```

The problem is that since garden uses maps for the CSS declarations I couldn't figure out how to repeat same property into the declaration. There is any way to accomplish that?
