### ISSUE TITLE
Why is the property order in my CSS different from my Clojure?

### ISSUE THREAD

**Issue by martinklepsch** [noprompt/garden#67]
I just noticed that the property order is not maintained at least in some cases:

``` clojure
(garden.core/css [:span {:position "fixed" :left 0 :top "50px" :z-index 200 :width "50px" :height "50px" :color "white" :font-weight "bold" :font-size "1.3em" :border "2px white solid" :border-left "none" :background-color "transparent"}])
```

Returns CSS like this:

``` css
span {
  width: 50px;
  border-left: none;
  top: 50px;
  height: 50px;
  border:2px white solid;
  position: fixed;
  z-index: 200;
  font-weight: bold;
  font-size: 1.3em;
  background-color: transparent;
  color: white;
  left: 0;
}
```

In the given example it's intended that `border-left: none` removes the left border but since it comes before the general `border` property it is overridden.

Is this a bug or just something Garden doesn't support currently?
